config/routes.rb
Rails.application.routes.draw do
  
  root 'people#index'
  
  resources :people do
    collection do
      get 'search_form'
      post 'search'
      get 'filtered'
    end
    resources :matches do
      member do 
        post 'duplicate'
        post 'no_duplicate'
        post 'undecided'
        post 'reducers'
      end                
    end
  end
  
  namespace :admin do
    resources :tasks, only: [:index]
    resources :settings
    resources :jobs do
      collection do
        post 'match'
        post 'export'
      end
    end
  end
  
end

app/models/person.rb
class Person
  
  include Wisper::Publisher

  include Mongoid::Document
  include Mongoid::Timestamps  
  #include Hashie::Extensions::Mash
  include Mongoid::Elasticsearch
  
  elasticsearch!({
    # index name (prefix is added)
    index_name: "people-#{Rails.env}",

    # don't use global name prefix
    prefix_name: false,

    index_options: {
        # elasticsearch index definition
      settings: {
        index: {
          analysis: {
            filter: {
              dbl_metaphone: {
                type: "phonetic",
                  encoder: "double_metaphone"
                }
              },
              analyzer: {
                dbl_metaphone: {
                  replace: "true",
                  filter: ["standard", "lowercase", "dbl_metaphone"],
                  tokenizer: "standard"
                },
                email: {
                  tokenizer: "uax_url_email"
                }
              }
            }
          }
        },
        mappings: {
          "person" => {
            properties: {
              email: {
                type: "string",
                analyzer: "email"
              },
              full_name: {
                type: "string",
                analyzer: "dbl_metaphone"
              },
              preferred_name: {
                type: "string",
                analyzer: "dbl_metaphone"
              }
            }
          }
        }
      },  
    wrapper: :load
  })

  field :auth_sig_id, type: String # signing_auth  
  field :contact_id, type: String # contact_person
  field :client_id, type: String # contact_person, legal_party, client
  field :communication_type, type: String # contact_person, legal_party, client
  field :department, type: String # contact_person
  field :dob, type: Date # legal_party, client
  field :deceased_date, type: Date # legal_party
  field :email, type: String # contact_person, client 
  field :fax_area, type: String # contact_person
  field :fax_no, type: String # contact_person
  field :fax_country, type: String # contact_person  
  field :from_date, type: Date # signing_auth    
  field :full_name, type: String # agg(first_name, surname), contact_person, legal_party, client  
  field :gender, type: String # legal_party
  field :hits, type: Integer  
  field :legal_party_id, type: String # legal_party
  field :legal_name, type: String # client  
  field :preferred_name, type: String # legal party, client
  field :phone_area, type: String # contact_person
  field :phone, type: String # contact_person
  field :phone_country, type: String # contact_person
  field :relationship, type: String # contact_person
  field :signing_client_id, type: String # signing_auth    
  field :title, type: String # legal_party
  field :to_date, type: Date # signing_auth    
  field :type, type: Symbol
  
  embeds_many :addresses
  
  embeds_many :matches  
  

=begin
  
select c.Client_ID, Client_Type, Legal_Name, isnull(Title, '') [Title], First_Names, Surname, isnull(Preferred_Name, '') [Preferred_Name]
, isnull(convert(varchar(10), Commencement_Date, 120), '') as DOB, isnull(e.Email, '') [Email]
, isnull(addr.Communication_Type, '') [Communication_Type], isnull(addr.Postal_Address_Line_1, '') [Postal_Address_Line_1]
, isnull(addr.Postal_Address_Line_2, '') [Postal_Address_Line_2], isnull(addr.Postal_Address_Line_3, '') [Postal_Address_Line_3]
, isnull(addr.Postal_City, '') [Postal_City], isnull(addr.Postal_Country, '') [Postal_Country], isnull(addr.Postal_Post_Code, '') [Postal_Post_Code]
, isnull(addr.Physical_Address_Line_1, '') [Physical_Address_Line_1], isnull(addr.Physical_Address_Line_2, '') [Physical_Address_Line_2]
, isnull(addr.Physical_Address_Line_3, '') [Physical_Address_Line_3], isnull(addr.Physical_City, '') [Physical_City]
, isnull(addr.Physical_Country, '') [Physical_Country], isnull(addr.Physical_Post_Code, '') [Physical_Post_Code]
from Client c

-- Client_ID, Legal_Party_ID, First_Name, Surname, Preferred_Name, Title, DOB, Gender, Deceased_Date
select Client_ID, Legal_Party_ID, First_Name, Surname
, isnull(Preferred_Name, '') [Preferred_Name]
, isnull(Title, '') [Title]
, isnull(convert(varchar(10), DOB, 120), '') as DOB
, isnull(Gender, '') [Gender]
, isnull(convert(varchar(10), Deceased_Date, 120), '') [Deceased_Date]
from Legal_Parties

-- Contact_ID, Client_ID, First_Name, Surname, Relationship, Address_Line_1, Address_Line_2, Address_Line_3, City, Country, Post_Code, Department, Phone_Area, Phone, Phone_Country, Fax_Area,Fax_No, Fax_Country,Email 
select Contact_ID, Client_ID, First_Name, Surname, Relationship
, isnull(Address_Line_1, '') [Address_Line_1]
, isnull(Address_Line_2, '') [Address_Line_2]
, isnull(Address_Line_3, '') [Address_Line_3]
, isnull(City, '') [City]
, isnull(Post_Code, '') [Post_Code]
, isnull(Department, '') [Department]
, isnull(Phone_Country, '') [Phone_Country], isnull(Phone_Area, '') [Phone_Area], isnull(Phone, '') [Phone]
, isnull(Fax_Country, '') [Fax_Country], isnull(Fax_Area, '') [Fax_Area], isnull(Fax_No, '') [Fax_No]
, isnull(Email, '') [Email]
from Contact_Person

-- Auth_Sig_ID, Client_ID, Signing_Client_ID, First_Name, Surname, From_Date, To_Date
Select Auth_Sig_ID, Client_ID
, isnull(Signing_Client_ID, '') [Signing_Client_ID]
, isnull(First_Name, '') [First_Name]
, isnull(Surname, '') [Surname]
, isnull(convert(varchar(10), From_Date, 120), '') [From_Date]
, isnull(convert(varchar(10), To_Date, 120), '') [To_Date]
from Signing_Authority

  
=end
  
  def self.delete_index
    #self.__elasticsearch__.client.indices.delete index: self.index_name rescue nil
  end
  
  def self.create_index
    self.es.index_all  
  end
  
  def self.comparison
    self.all.each do |person|
      s = self.es.search(comp_search_dsl(person))
      #s = self.es.search "+full_name:#{person.full_name}"
      person.match s.hits
    end
  end
  
  def self.individual_comparison(person)
    self.es.search(comp_search_dsl(person))
  end
  
  def self.comp_search_dsl(person)
    {
      body: {
        query: {
          bool: {
            must_not: {
              match: {
                _id: person.id.to_s
              }
            },
            must: {
              match: {
                full_name: person.full_name
              }
            },
            should: self.add_shoulds(person)
          }
        }        
      }
    }
  end
  
  def self.add_shoulds(person)
    shoulds = []
    #shoulds << {match: {email: person.email}} if person[:email]
    #shoulds << {match: {email: person.preferred_name}} if person[:preferred_name]
    shoulds
  end
  
  def self.load(person: nil)
    types = {contact: :contact_id, legal_party: :legal_party_id, client: :client_id}
    id = types[person[:type]]
    p = self.where(id => person[id]).first
    p ? p.update_me(person: person) : self.new.create_me(person: person)
  end
  
  def self.general_search(q: nil)
    self.es.search(
      {
        body: {
          query: {
            query_string: {
              query: q
            }          
          }
        }
      }
    )
  end
  
  def self.generate_download(people, filter)
    Jbuilder.encode do |json| 
      json.filter_name filter.name
      json.filter_desc filter.desc
      json.count people.count
      json.people people do |person|
        json.id person.id.to_s
        json.set! person.type_id_name, person.type_id_id
        json.client_id person.client_id
        json.type person.type
        json.full_name person.full_name
        json.total_matches person.matches.count
        json.filtered_matches person.matches.get_matches("true") do |match|
          if filter.fired?(match)
            json.score match.score
            json.set! :reducers, match.reducers
#              match.reducers.each {|red| json.set! red["matcher"], red["match"] }
#            end
            @dup = match.dup_person
            json.matched_person do 
              json.id @dup.id.to_s
              json.full_name @dup.full_name
              json.set! @dup.type_id_name, @dup.type_id_id
              json.client_id @dup.client_id
              json.type @dup.type
              json.full_name @dup.full_name

            end
          end
        end
      end
    end
  end
  
  
  def create_me(person: nil)
    self.update_attrs(person: person)
    maintain_addresses(address_attrs: Address.extract_address_attrs(person))
    self.save
    publish(:successful_person_create_event, self)
  end
  
  def update_me(person: nil)
    self.update_attrs(person: person)
    self.save
    publish(:successful_person_update_event, self)
  end
  
  
  def update_attrs(person: nil)
    person.each {|name, value| self.send("#{name}=", value) unless handled_attrs.include? name}
    maintain_addresses(address_attrs: Address.extract_address_attrs(person))
    self.full_name = {first_name: person[:first_name], surname: person[:surname]}
    [:dob, :deceased_date, :from_date, :to_date].each do |date|
      d = Date.parse(person[date]) rescue nil
      self.send("#{date}=", d) if d
    end
  end
  
  def date_it(date)
    Date.parse(date) if date
  end
  
  def handled_attrs
    [:address_line_1, :address_line_2, :address_line_3, 
      :city, :country, :post_code, 
      :first_name, :surname, :dob, :deceased_date, :from_date, :to_date,
      :client_type,
      :postal_address_line_1, :postal_address_line_2, :postal_address_line_3, :postal_city, :postal_country, :postal_post_code, 
      :physical_address_line_1,:physical_address_line_2, :physical_address_line_3, :physical_city, :physical_country, :physical_post_code
    ]
  end
  
  def maintain_addresses(addresses)
    # there is no way to determine which address to update, so delete them first
    self.addresses.delete_all
    addresses[:address_attrs].each {|addr| self.addresses << Address.create_me(addr: addr) }
  end
  
  
  def as_indexed_json(options={})
    as_json(except: [:id, :_id, :matches])
  end
  
  def match_decision(decision: nil, match: nil)

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
    @people = Person.order_by(hits: :desc, full_name: :asc).paginate(page: params[:page])
  end
  
  def show
    @person = Person.find(params[:id])
  end
  
  def search_form
  end
  
  def filtered
    @filter = Setting.value_for('min_score')
    @people = Person.gt('matches.score' => @filter).order_by(hits: :desc, full_name: :asc).paginate(page: params[:page])
    render 'index'
  end
  
  def search
    @people = Person.general_search(q: params[:search])
  end
  
end

app/views/people/_icon_bar.html.erb
<div class="icon-bar large-vertical four-up">
   <%= link_to(people_path, class: "item") do %>
      <i class="fi-torso"></i>
      <label>All People</label>
   <% end %>
   <%= link_to(filtered_people_path, class: "item") do %>
      <i class="fi-magnifying-glass"></i>
      <label>Filtered</label>
   <% end %>
   
   <%= link_to(search_form_people_path, class: "item", remote: true) do %>
      <i class="fi-magnifying-glass"></i>
      <label>Search</label>
   <% end %>
   
</div>

app/views/people/_people.html.erb
<% if @filter %>
  <dl class="sub-nav">
   <dt>Score Filter</dt>
   <dd class="active">
     <%= @filter %>
   </dd>
  </dl>
<% end %>

<% @people.each do |person|%>
  <div class="panel">
   <div class="row">
      <div class="small-1 columns">
         <i class="fi-<%=type_icon(person.type) %> size-30"></i>
      </div>
      <div class="small-11 columns">
         <h5><%= link_to person.full_name, person_path(person), remote: true %></h5>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
         <dl class="sub-nav">
           <dt>Filtered Match</dt>
           <dd class="active">
              <%= link_to person.matches.filtered_match.count, person_matches_path(person, filtered: true), remote: true%>
           </dd>
           <dt>Total Match</dt>
           <dd class="active">
              <%= link_to person.matches.count, person_matches_path(person, filtered: false), remote: true%>
           </dd>           
         </dl>
      </div>
   </div>
   <div class="row">
     <dl class="sub-nav">
       <dt>Decisions</dt>
       <dd class="active">
          <%= link_to person.match_decisions_count, "#"%>
       </dd>
     </dl>
     
   </div>
 </div>
   
<% end %>


<%= will_paginate @people, renderer: FoundationPagination::Rails %>

app/views/people/_person.html.erb
<div class="panel">
  <h5><i class="fi-<%=type_icon(person.type) %> size-30"></i><%= person.full_name %></h5>
</div>

<div class="row">
   <div class="large-5 columns">
      <h5>Title</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.title%></h5>
   </div>   
</div>

<div class="row">
   <div class="large-5 columns">
      <h5>Preferred Name</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.try(:preferred_name) %></h5>
   </div>   
</div>

<div class="row">
   <div class="large-5 columns">
      <h5>Gender</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.try(:gender) %></h5>
   </div>   
</div>

<div class="row">
   <div class="large-5 columns">
      <h5>dob</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.dob%></h5>
   </div>   
</div>


<div class="row">
   <div class="large-5 columns">
      <h5>Type</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.type%></h5>
   </div>   
</div>

<div class="row">
   <div class="large-5 columns">
      <h5>Client ID</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.client_id%></h5>
   </div>   
</div>

<div class="row">
   <div class="large-5 columns">
      <h5>Relationship</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.relationship%></h5>
   </div>   
</div>

<div class="row">
   <div class="large-5 columns">
      <h5>Phone</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.full_phone_number%></h5>
   </div>   
</div>
<div class="row">
   <div class="large-5 columns">
      <h5>Fax</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.full_fax_number%></h5>
   </div>   
</div>
<div class="row">
   <div class="large-5 columns">
      <h5>Email</h5>
   </div>
   <div class="large-7 columns">
      <h4 class="subheader"><%= person.email%></h5>
   </div>   
</div>
<div class="row">
   <div class="large-5 columns">
      <h5>Address</h5>
   </div>
   <div class="large-7 columns">
      <% person.addresses.each do |addr| %>
         <%= addr.address_line_1%></br>
         <%= addr.address_line_2%></br>
         <%= addr.address_line_3%></br>
         <%= addr.city%></br>
         <%= addr.country%></br>
         <%= addr.post_code%></br>
      <% end %>
   </div>   
</div>

app/views/people/_search.html.erb
<% @people.results.each do |person|%>
   <div class="row">
      <div class="small-3 columns">
         <h5><%= person.full_name %></h5>
      </div>
      <div class="small-5 end columns">
         <dl class="sub-nav">
           <dt>Matches</dt>
           <dd class="active">
           </dd>
         </dl>
      </div>
   </div>
   
<% end %>

app/views/people/_search_form.html.erb
<%= form_tag(search_people_path, html: { class: "custom"}, remote: true) do %>
   <div class="row">
     <div class="small-3 columns">
       <%= label_tag :search, nil, class: "right inline"%>
     </div>
     <div class="small-4 columns end">
         <%= text_field_tag :search%>
     </div> 
   </div>
<% end %>

app/views/people/index.html.erb
<div class="row">
   <div class="large-2 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="large-10 columns">
      <div class="row">
         <div id="search"></div>
      </div>
      <div class="row">
         <div class="large-7 columns">
            <div id = "people">
               <%= render 'people'%>
            </div>
         </div>
         <div class="large-5 columns">
            <div id='person'></div>
         </div>
         
      </div>
   </div>
</div>