config/routes.rb
Rails.application.routes.draw do
  
  root 'people#index'
  
  resources :people do
    collection do
      get 'search_form'
      post 'search'
      get 'filtered'
    end
    resources :matches do
      member do 
        post 'duplicate'
        post 'no_duplicate'
        post 'undecided'
        post 'reducers'
      end                
    end
  end
  
  namespace :admin do
    resources :tasks, only: [:index]
    resources :settings
    resources :jobs do
      collection do
        post 'match'
        post 'export'
      end
    end
  end
  
end

app/models/setting.rb
class Setting
  
  include Wisper::Publisher

  include Mongoid::Document
  include Mongoid::Timestamps  
  
  field :name, type: String
  field :value_int, type: Integer
  field :value_float, type: Float  
  field :value_string, type: String
  field :type, type: Symbol
  
  def self.types
    [["String", :string], ["Integer", :integer], ["Float", :float]]
  end
  
  def self.value_for(name)
    set = Setting.where(name: name).first
    set.nil? ? nil : set.value
  end    
    
  def create_me(config: nil)
    update_attrs(config: config)
    self.save
    publish(:successful_setting_create_event, self)
  end

  def update_me(config: nil)
    update_attrs(config: config)
    self.save
    publish(:successful_setting_update_event, self)
  end
  
  def value
    case self.type
    when :string
      self.value_string
    when :integer
      self.value_int
    when :float
      self.value_float
    else
      raise
    end
  end
  
  def update_attrs(config: nil)
    self.name = config[:name]
    self.type = config[:type]
    case self.type
    when :string
      self.value_string = config[:value]
    when :integer
      self.value_int = config[:value].to_i
    when :float
      self.value_float = config[:value].to_f      
    else
      raise
    end
  end  
  
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  
  def index
    @settings = Setting.all
  end
  
  def update
    setting = Setting.find(params[:id])
    setting.subscribe self
    setting.update_me(config: params[:setting])
  end
    
  # Events
  
  def successful_setting_update_event(setting)
    redirect_to admin_tasks_path
  end

  def successful_setting_create_event(setting)
    redirect_to admin_tasks_path
  end

    
end

app/views/admin/settings/_form.html.erb
<%= form_for(setting, url: admin_setting_path(setting), html: { class: "custom"}) do |f| %>
   <div class="row">
     <div class="small-2 columns">
       <%= f.label :name, class: "right inline"%>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :name, placeholder: "Config Name" %>
     </div> 
   </div>
   <div class="row">
     <div class="small-2 columns">
       <%= f.label :value, class: "right inline" %>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :value, placeholder: "Value" %>
     </div> 
   </div>

   <div class="row">
     <div class="small-2 columns">
       <%= f.label :type, class: "right inline" %>
     </div>
     <div class="small-10 columns">
       <%= f.select(:type, options_for_select(Setting.types, setting.type), :include_blank => true, :prompt => "Select Type", :class => "medium")%>
     </div> 
   </div>
   <div class="row">
     <div class="small-10 small-offset-2 columns">
       <%= f.submit 'Submit', :class => 'button small' %>
     </div>
   </div>
   
   

<% end %>

app/views/admin/settings/_index.html.erb
<% @settings.each do |setting| %>
  <%= render partial: 'form', locals: {setting: setting}%>
<% end %>