config/routes.rb
Rails.application.routes.draw do
  
  root 'people#index'
  
  resources :people do
    collection do
      get 'search_form'
      post 'search'
      get 'filtered'
    end
    resources :matches do
      member do 
        post 'duplicate'
        post 'no_duplicate'
        post 'undecided'
        post 'reducers'
      end                
    end
  end
  
  namespace :admin do
    resources :tasks, only: [:index]
    resources :settings
    resources :jobs do
      collection do
        post 'match'
        post 'export'
      end
    end
  end
  
end

app/models/match.rb
class Match
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  field :score, type: Float
  #field :matched_person, type: BSON::ObjectId
  field :matched_person, type: String
  field :reducers, type: Hash
  field :state, type: Symbol
  
  embedded_in :person
  
  scope :all_matches, -> {desc(:score)}
  
  def self.get_matches(filtered)
    if filtered == "true"
      self.filtered_match
    else
      self.all_matches
    end
  end
  
  def self.filtered_match
    self.gt(score: Setting.value_for('min_score')).desc(:score)
  end
  
  def self.reducer_state_for(reducer)
    self.in(reducers: {"matcher" => reducer.to_s, "match" => true})
  end
  
  
  def self.create_me(result)
    m = self.new
    m.update_attrs(result)
    m
  end
    
  def update_attrs(result) # result is a hit as Hashie::Mash
    self.score = result._score
    self.matched_person = result._id
    self
  end
  
  def run_reducers 
    self.reducers = Matchers.new.process(person: self.person, potential: self.dup_person)
    self.save
    self.reducers
  end
  
  def reducer_state_for(reducer)
    self.reducers.find {|c| c[:matcher] == reducer.to_s}["match"]
  end
  
  def dup_person
    Person.find(matched_person)
  end
  
  def decision(state)
    self.state = state
    self
  end
  
  def decision_made
    state == :duplicate || state == :no_duplicate
  end
  
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  
  def index
    @person = Person.find(params[:person_id])
    @apply_filter = params[:filtered]
  end
  
  def show
    @person = Person.find(params[:person_id])
    @match = @person.matches.find(params[:id])
    @dup = @match.dup_person
  end

  def duplicate
    @person = Person.find(params[:person_id])
    @person.subscribe self
    @person.match_decision(decision: :duplicate, match: params[:id])
  end

  def no_duplicate
    @person = Person.find(params[:person_id])
    @person.subscribe self
    @person.match_decision(decision: :no_duplicate, match: params[:id])
  end

  def undecided
    @person = Person.find(params[:person_id])
    @person.subscribe self
    @person.match_decision(decision: :undecided, match: params[:id])
  end
  
  # events
  
  def successful_match_decision_event(person, match)
    redirect_to person_match_path(person, match)
  end

  
end

app/views/matches/_matches.html.erb
<%= render partial: 'people/person', locals: {person: match.dup_person}%>

<div data-alert class="alert-box">
  Decision: <%= match.state%>
  <a href="#" class="close">&times;</a>
</div>     


<%= render partial: 'reducers', locals: {match: match}%>

<%= link_to 'View Match', person_match_path(@person, match), class: "button"%>

app/views/matches/_person_matches.html.erb
<div class="panel">
  <h5><i class="fi-<%=type_icon(@person.type) %> size-30"></i><%= @person.full_name %></h5>
</div>
<% @person.matches.get_matches(@apply_filter).each do |match| %>
   <%= render partial: 'matches', locals: {match: match} %>
<% end %>

app/views/matches/_reducers.html.erb
<div class="row">
   <dl class="sub-nav">
     <dt>Reducers</dt>
     <% match.run_reducers.each do |reduce| %>
        <dd class=<%= active_test(reduce[:match]) %>><a href="#"><%= reduce[:matcher] %></a></dd>
     <% end %>
   </dl>   
</div>
<div class="row">
   <dl class="sub-nav">
     <dt>Match Score</dt>
     <dd><%= match.score %></dd>
   </dl>   
</div>

app/views/matches/show.html.erb
<div class="row">
  <div class="large-2 columns">
    <h3 class="subheader">Property</h3>
  </div>
  <div class="large-3 columns">
    <h3 class="subheader">Master</h3>
  </div>
  <div class="large-3 end columns">
    <h3 class="subheader">Potential Match</h3>
  </div>  
</div>

<div class="row">
  <div class="large-2 columns">
    <h5>Type</h5>
  </div>
  <div class="large-3 columns">
    <i class="fi-<%=type_icon(@person.type) %> size-30"></i>
  </div>
  <div class="large-3 end columns">
    <i class="fi-<%=type_icon(@dup.type) %> size-30"></i>
  </div>  
</div>


<div class="row">
  <div class="large-2 columns">
    <h5>Full Name</h5>
  </div>
  <div class="large-3 columns">
    <%= @person.full_name%>
  </div>
  <div class="large-3 end columns">
    <%= @dup.full_name%>    
  </div>  
</div>
<div class="row">
  <div class="large-2 columns">
    <h5>Gender</h5>
  </div>
  <div class="large-3 columns">
    <%= @person.try(:gender)%>
  </div>
  <div class="large-3 end columns">
    <%= @dup.try(:gender)%>    
  </div>  
</div>

<div class="row">
  <div class="large-2 columns">
    <h5>DoB</h5>
  </div>
  <div class="large-3 columns">
    <%= @person.try(:dob)%>
  </div>
  <div class="large-3 end columns">
    <%= @dup.try(:dob)%>    
  </div>  
</div>

<div class="row">
  <div class="large-2 columns">
    <h5>Preferred Name</h5>
  </div>
  <div class="large-3 columns">
    <%= @person.try(:preferred_name)%>
  </div>
  <div class="large-3 end columns">
    <%= @dup.try(:preferred_name)%>    
  </div>  
</div>


<div class="row">
  <div class="large-2 columns">
    <h5>Client ID</h5>
  </div>
  <div class="large-3 columns">
    <%= @person.client_id%>
  </div>
  <div class="large-3 end columns">
    <%= @dup.client_id%>    
  </div>  
</div>
<div class="row">
  <div class="large-2 columns">
    <h5>Email</h5>
  </div>
  <div class="large-3 columns">
    <%= @person.email%>
  </div>
  <div class="large-3 end columns">
    <%= @dup.email%>    
  </div>  
</div>
<div class="row">
   <div class="large-2 columns">
      <h5>Address</h5>
   </div>
   <div class="large-3 columns">
      <% @person.addresses.each do |addr| %>
         <%= addr.address_line_1%></br>
         <%= addr.address_line_2%></br>
         <%= addr.address_line_3%></br>
         <%= addr.city%></br>
         <%= addr.country%></br>
         <%= addr.post_code%></br>
      <% end %>
   </div>   
   <div class="large-3 end columns">
      <% @dup.addresses.each do |addr| %>
         <%= addr.address_line_1%></br>
         <%= addr.address_line_2%></br>
         <%= addr.address_line_3%></br>
         <%= addr.city%></br>
         <%= addr.country%></br>
         <%= addr.post_code%></br>
      <% end %>
   </div>   
</div>

<%= render partial: 'reducers', locals: {match: @match}%>

<div class="row">
  <div data-alert class="alert-box">
    <h5><%= @match.state%></h5>
    <a href="#" class="close">&times;</a>
  </div>
</div>
<div class="row">
   <div class="large-6 end columns">
    <div class="icon-bar three-up">
      <%= link_to duplicate_person_match_path(@person, @match), method: :post do %>
        <i class="fi-check size-60"></i>
        <label>Match</label>
      <% end %>
      <%= link_to no_duplicate_person_match_path(@person, @match), method: :post do %>
        <i class="fi-x size-60"></i>
        <label>No Match</label>    
      <% end %>
      <%= link_to undecided_person_match_path(@person, @match), method: :post do %>
        <i class="fi-save size-60"></i>
        <label>Decide Later</label>    
      <% end %>      
    </div>
  </div>
</div>